In [1]:
import pandas as pd

In [3]:
pares = pd.read_parquet(r"C:\Users\lfmelo\Documents\Github\TJGO_Projeto-Processos-Pessoas-Vulneraveis\data\pares_parecidos.parquet")
pares.head()

   doc_1  doc_2  score_hypermatch_lematizado  score_tfidf_global
0   2145   4691                          1.0                 1.0
1   1912   2027                          1.0                 1.0
2   3468   8294                          1.0                 1.0
3   7314   7489                          1.0                 1.0
4   3444   7574                          1.0                 1.0

In [4]:
df = pd.read_parquet(r"C:\Users\lfmelo\Documents\Github\TJGO_Projeto-Processos-Pessoas-Vulneraveis\data\dataset_enriquecido_10062026_lematizado.parquet")
df.head()

,TEMA_ORIGEM,TEMA_CODIGO,inteiro_teor,inteiro_teor_lematizado
0,STF,1002,>>>>>inicio<<<<<\nDISTRIBUIÇÃO 2§ Vara Feitos ...,> > > > > inicio < < < < < \n DISTRIBUIÇÃO 2§ ...
1,STF,1002,>>>>>inicio<<<<<\nDIstribuitio ao I ESTADO DE ...,> > > > > inicio < < < < < \n DIstribuitio a o...
2,STF,1002,Erro Parser>>>>>inicio<<<<<\nSÚMULAS As seçõe...,Erro Parser>>>>>inicio < < < < < \n SÚMULAS ...
3,STF,1002,Erro Parser>>>>>inicio<<<<<\nMeritíssimo Juízo...,Erro Parser>>>>>inicio < < < < < \n Meritíssim...
4,STF,1002,Erro Parser>>>>>inicio<<<<<\nAutos nº 0129185-...,Erro Parser>>>>>inicio < < < < < \n auto nº 01...

In [6]:
df_new = df.reset_index()

In [7]:
df_new.head()

,index,TEMA_ORIGEM,TEMA_CODIGO,inteiro_teor,inteiro_teor_lematizado
0,0,STF,1002,>>>>>inicio<<<<<\nDISTRIBUIÇÃO 2§ Vara Feitos ...,> > > > > inicio < < < < < \n DISTRIBUIÇÃO 2§ ...
1,1,STF,1002,>>>>>inicio<<<<<\nDIstribuitio ao I ESTADO DE ...,> > > > > inicio < < < < < \n DIstribuitio a o...
2,2,STF,1002,Erro Parser>>>>>inicio<<<<<\nSÚMULAS As seçõe...,Erro Parser>>>>>inicio < < < < < \n SÚMULAS ...
3,3,STF,1002,Erro Parser>>>>>inicio<<<<<\nMeritíssimo Juízo...,Erro Parser>>>>>inicio < < < < < \n Meritíssim...
4,4,STF,1002,Erro Parser>>>>>inicio<<<<<\nAutos nº 0129185-...,Erro Parser>>>>>inicio < < < < < \n auto nº 01...

In [11]:
pd.set_option('display.max_colwidth', 600)

In [14]:
df_new[df_new["index"].isin([7314,7489,3444,7574])]

,index,TEMA_ORIGEM,TEMA_CODIGO,inteiro_teor,inteiro_teor_lematizado
3444,3444,STJ,1015,">>>>>inicio<<<<<\nN 133438.2 - A55 - M - Idec - Diego Mattos Excelentíssimo Senhor Doutor Desembargador Norival Santomé, integrante da Sexta Câmara Cível do Egrégio Tribunal de Justiça de Goiás. Autos de Agravo de Instrumento n.º 0094962.33.2016.8.09.0000 HSBC BANK BRASIL S.A - BANCO MÚLTIPLO, já qualificado nos autos de Agravo de Instrumento em epígrafe, em que é parte Agravante, sendo parte Agravada ESPÓLIO DE VALDECY PEREIRA DA SILVA JÚNIOR, comparece respeitosamente perante Vossa Excelência, por seus advogados devidamente constituídos, para interpor, tempestivamente, AGRAVO INTERNO con...","> > > > > inicio < < < < < N 133438.2 - A55 - M - Idec - Diego Mattos Excelentíssimo Senhor doutor desembargador Norival Santomé , integrante de o Sexta Câmara Cível de o Egrégio Tribunal de Justiça de Goiás . Autos de Agravo de Instrumento n.º 0094962.33.2016.8.09.0000 HSBC BANK BRASIL S.A - BANCO MÚLTIPLO , já qualificar em o auto de Agravo de Instrumento em epígrafe , em que ser parte agravante , ser parte Agravada ESPÓLIO de VALDECY PEREIRA de o SILVA JÚNIOR , comparecer respeitosamente perante Vossa Excelência , por seu advogado devidamente constituír , para interpor , tempestivamente..."
7314,7314,STJ,919,">>>>>inicio<<<<<\nCarlos Æberto Pereira +0 Advogado Excelentíssimo Senhor Doutor Juiz de Direito da • Vara Cível da Comarca de Porangatu, GO. . . . . . . .. MARCONE VIEIRA VISCONDE, brasileiro, separado judicialmente, funcionário público estadual, portador do CPF/MF n° 057.735.711-53, residente e domiciliado na Rua do Trabalho, n° 440, Edifício Palmares, Bloco G, Apto. 303, Setor dos Rodoviários, Goiânia, GO, CEP 74.430- 450, vem, respeitosamente, à presença de Vossa Excelência, por seus advogados infra-assinado (doc. anexo), para propor a presente AÇÃO DE LARATÓRIA DENULIDADE C.C...","> > > > > inicio < < < < < \n Carlos Æberto Pereira +0r Advogado Excelentíssimo Senhor Doutor Juiz de Direito de o • Vara Cível de o Comarca de Porangatu , GO . . . . . . . .. MARCONE VIEIRA VISCONDE , brasileiro , separar judicialmente , funcionário público estadual , portador de o CPF / MF n ° 057.735. 711-53 , residente e domiciliar em o Rua de o Trabalho , n ° 440 , Edifício Palmares , Bloco G , Apto . 303 , Setor de o Rodoviários , Goiânia , GO , CEP 74.430- 450 , vir , respeitosamente , a o presença de Vossa Excelência , por seu advogado infra-assinar ( doc . anexo ) ..."
7489,7489,STJ,935,">>>>>inicio<<<<<\nCarlos Æberto Pereira +0 Advogado Excelentíssimo Senhor Doutor Juiz de Direito da • Vara Cível da Comarca de Porangatu, GO. . . . . . . .. MARCONE VIEIRA VISCONDE, brasileiro, separado judicialmente, funcionário público estadual, portador do CPF/MF n° 057.735.711-53, residente e domiciliado na Rua do Trabalho, n° 440, Edifício Palmares, Bloco G, Apto. 303, Setor dos Rodoviários, Goiânia, GO, CEP 74.430- 450, vem, respeitosamente, à presença de Vossa Excelência, por seus advogados infra-assinado (doc. anexo), para propor a presente AÇÃO DE LARATÓRIA DENULIDADE C.C...","> > > > > inicio < < < < < \n Carlos Æberto Pereira +0r Advogado Excelentíssimo Senhor Doutor Juiz de Direito de o • Vara Cível de o Comarca de Porangatu , GO . . . . . . . .. MARCONE VIEIRA VISCONDE , brasileiro , separar judicialmente , funcionário público estadual , portador de o CPF / MF n ° 057.735. 711-53 , residente e domiciliar em o Rua de o Trabalho , n ° 440 , Edifício Palmares , Bloco G , Apto . 303 , Setor de o Rodoviários , Goiânia , GO , CEP 74.430- 450 , vir , respeitosamente , a o presença de Vossa Excelência , por seu advogado infra-assinar ( doc . anexo ) ..."
7574,7574,STJ,948,">>>>>inicio<<<<<\nN 133438.2 - A55 - M - Idec - Diego Mattos Excelentíssimo Senhor Doutor Desembargador Norival Santomé, integrante da Sexta Câmara Cível do Egrégio Tribunal de Justiça de Goiás. Autos de Agravo de Instrumento n.º 0094962.33.2016.8.09.0000 HSBC BANK BRASIL S.A - BANCO MÚLTIPLO, já qualificado nos autos de Agravo de Instrumento em epígrafe, em que é parte Agravante, sendo parte Agravada ESPÓLIO DE VALDECY PEREIRA DA SILVA JÚNIOR, comparece respeitosamente perante Vossa Excelência, por seus advogados devidamente constituídos, para interpor, tempestivamente, AGRAVO INTERNO con...","> > > > > inicio < < < < < N 133438.2 - A55 - M - Idec - Diego Mattos Excelentíssimo Senhor doutor desembargador Norival Santomé , integrante de o Sexta Câmara Cível de o Egrégio Tribunal de Justiça de Goiás . Autos de Agravo de Instrumento n.º 0094962.33.2016.8.09.0000 HSBC BANK BRASIL S.A - BANCO MÚLTIPLO , já qualificar em o auto de Agravo de Instrumento em epígrafe , em que ser parte agravante , ser parte Agravada ESPÓLIO de VALDECY PEREIRA de o SILVA JÚNIOR , comparecer respeitosamente perante Vossa Excelência , por seu advogado devidamente constituír , para interpor , tempestivamente..."

In [15]:
df_entidades = pd.read_parquet(r"data/entidades_extracao.parquet")

In [17]:
df_entidades['label'].unique()

<ArrowStringArray>
[        'PROCESSO_CNJ',                  'OAB',               'CLASSE',
              'ASSUNTO',              'COMARCA',                 'VARA',
 'ORGAO_OU_INSTITUICAO',                'LOCAL',                 'MISC',
               'PESSOA',                 'CNPJ',                  'CPF',
             'ADVOGADO',                  'REU']
Length: 14, dtype: str

In [22]:
df_exportado = pd.read_csv(r"C:\Users\lfmelo\Documents\Github\TJGO_Projeto-Processos-Pessoas-Vulneraveis\NER\exportacao_assunto_guarda_alimentos_crianca_adolescente_violencia_domestica.csv")

In [28]:
df_exportado['id_processo'].unique()

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 16, 17, 18, 19, 20,
       21, 22, 25, 26, 27, 28, 29, 30, 31, 32, 33, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45, 46, 47, 48, 49, 51, 52, 53, 54, 55, 56, 57, 58,
       59, 60, 61, 62, 63, 64, 65, 66, 67, 69, 72, 74, 75, 80, 83, 84, 87,
       89, 90, 91, 92, 93, 97, 98, 99])